// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: common/in/ssws.proto

package in

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ID int32

const (
	ID_GRPC_GM_CMD_DEFAULT  ID = 0
	ID_GRPC_GM_CMD_ACTIVITY ID = 1 //通用类活动
)

// Enum value maps for ID.
var (
	ID_name = map[int32]string{
		0: "GRPC_GM_CMD_DEFAULT",
		1: "GRPC_GM_CMD_ACTIVITY",
	}
	ID_value = map[string]int32{
		"GRPC_GM_CMD_DEFAULT":  0,
		"GRPC_GM_CMD_ACTIVITY": 1,
	}
)

func (x ID) Enum() *ID {
	p := new(ID)
	*p = x
	return p
}

func (x ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ID) Descriptor() protoreflect.EnumDescriptor {
	return file_common_in_ssws_proto_enumTypes[0].Descriptor()
}

func (ID) Type() protoreflect.EnumType {
	return &file_common_in_ssws_proto_enumTypes[0]
}

func (x ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ID.Descriptor instead.
func (ID) EnumDescriptor() ([]byte, []int) {
	return file_common_in_ssws_proto_rawDescGZIP(), []int{0}
}

type TestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_in_ssws_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_in_ssws_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_common_in_ssws_proto_rawDescGZIP(), []int{0}
}

func (x *TestRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TestReplay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Replay string `protobuf:"bytes,1,opt,name=replay,proto3" json:"replay,omitempty"`
}

func (x *TestReplay) Reset() {
	*x = TestReplay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_in_ssws_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestReplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestReplay) ProtoMessage() {}

func (x *TestReplay) ProtoReflect() protoreflect.Message {
	mi := &file_common_in_ssws_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestReplay.ProtoReflect.Descriptor instead.
func (*TestReplay) Descriptor() ([]byte, []int) {
	return file_common_in_ssws_proto_rawDescGZIP(), []int{1}
}

func (x *TestReplay) GetReplay() string {
	if x != nil {
		return x.Replay
	}
	return ""
}

type GMRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd  uint32         `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Sid  uint32         `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
	Data *GMRequestByte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GMRequest) Reset() {
	*x = GMRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_in_ssws_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMRequest) ProtoMessage() {}

func (x *GMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_in_ssws_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMRequest.ProtoReflect.Descriptor instead.
func (*GMRequest) Descriptor() ([]byte, []int) {
	return file_common_in_ssws_proto_rawDescGZIP(), []int{2}
}

func (x *GMRequest) GetCmd() uint32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *GMRequest) GetSid() uint32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *GMRequest) GetData() *GMRequestByte {
	if x != nil {
		return x.Data
	}
	return nil
}

//所有的协议对象
type GMRequestByte struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Modules  []uint32  `protobuf:"varint,1,rep,packed,name=modules,proto3" json:"modules,omitempty"`
	Activity *Activity `protobuf:"bytes,2,opt,name=activity,proto3" json:"activity,omitempty"`
}

func (x *GMRequestByte) Reset() {
	*x = GMRequestByte{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_in_ssws_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GMRequestByte) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMRequestByte) ProtoMessage() {}

func (x *GMRequestByte) ProtoReflect() protoreflect.Message {
	mi := &file_common_in_ssws_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMRequestByte.ProtoReflect.Descriptor instead.
func (*GMRequestByte) Descriptor() ([]byte, []int) {
	return file_common_in_ssws_proto_rawDescGZIP(), []int{3}
}

func (x *GMRequestByte) GetModules() []uint32 {
	if x != nil {
		return x.Modules
	}
	return nil
}

func (x *GMRequestByte) GetActivity() *Activity {
	if x != nil {
		return x.Activity
	}
	return nil
}

type GMReplay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret      uint32        `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Desc     string        `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Cmd      uint32        `protobuf:"varint,3,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Sid      uint32        `protobuf:"varint,4,opt,name=sid,proto3" json:"sid,omitempty"`
	Data     *GMReplayByte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	JsonData string        `protobuf:"bytes,6,opt,name=json_data,json=jsonData,proto3" json:"json_data,omitempty"`
}

func (x *GMReplay) Reset() {
	*x = GMReplay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_in_ssws_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GMReplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMReplay) ProtoMessage() {}

func (x *GMReplay) ProtoReflect() protoreflect.Message {
	mi := &file_common_in_ssws_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMReplay.ProtoReflect.Descriptor instead.
func (*GMReplay) Descriptor() ([]byte, []int) {
	return file_common_in_ssws_proto_rawDescGZIP(), []int{4}
}

func (x *GMReplay) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *GMReplay) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *GMReplay) GetCmd() uint32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *GMReplay) GetSid() uint32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *GMReplay) GetData() *GMReplayByte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GMReplay) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

type GMReplayByte struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RedisReplay []string `protobuf:"bytes,1,rep,name=redis_replay,json=redisReplay,proto3" json:"redis_replay,omitempty"`
}

func (x *GMReplayByte) Reset() {
	*x = GMReplayByte{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_in_ssws_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GMReplayByte) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMReplayByte) ProtoMessage() {}

func (x *GMReplayByte) ProtoReflect() protoreflect.Message {
	mi := &file_common_in_ssws_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMReplayByte.ProtoReflect.Descriptor instead.
func (*GMReplayByte) Descriptor() ([]byte, []int) {
	return file_common_in_ssws_proto_rawDescGZIP(), []int{5}
}

func (x *GMReplayByte) GetRedisReplay() []string {
	if x != nil {
		return x.RedisReplay
	}
	return nil
}

//通用类活动
type Activity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Add   []*ActivityInfo `protobuf:"bytes,1,rep,name=add,proto3" json:"add,omitempty"`
	DelId []uint32        `protobuf:"varint,2,rep,packed,name=del_id,json=delId,proto3" json:"del_id,omitempty"`
}

func (x *Activity) Reset() {
	*x = Activity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_in_ssws_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_common_in_ssws_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_common_in_ssws_proto_rawDescGZIP(), []int{6}
}

func (x *Activity) GetAdd() []*ActivityInfo {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *Activity) GetDelId() []uint32 {
	if x != nil {
		return x.DelId
	}
	return nil
}

type ActivityInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`       //活动唯一id
	Type  uint32 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`   //活动类型
	Name  string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`    //活动名字
	Start uint32 `protobuf:"varint,4,opt,name=start,proto3" json:"start,omitempty"` //开始时间
	End   uint32 `protobuf:"varint,5,opt,name=end,proto3" json:"end,omitempty"`     //活动结束时间
}

func (x *ActivityInfo) Reset() {
	*x = ActivityInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_in_ssws_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityInfo) ProtoMessage() {}

func (x *ActivityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_in_ssws_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityInfo.ProtoReflect.Descriptor instead.
func (*ActivityInfo) Descriptor() ([]byte, []int) {
	return file_common_in_ssws_proto_rawDescGZIP(), []int{7}
}

func (x *ActivityInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActivityInfo) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ActivityInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActivityInfo) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *ActivityInfo) GetEnd() uint32 {
	if x != nil {
		return x.End
	}
	return 0
}

var File_common_in_ssws_proto protoreflect.FileDescriptor

var file_common_in_ssws_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x69, 0x6e, 0x2f, 0x73, 0x73, 0x77, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x69, 0x6e, 0x22, 0x21, 0x0a, 0x0b, 0x54, 0x65,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x24, 0x0a,
	0x0a, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x70, 0x6c, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x70,
	0x6c, 0x61, 0x79, 0x22, 0x56, 0x0a, 0x09, 0x47, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x63,
	0x6d, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x73, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x6e, 0x2e, 0x47, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x42, 0x79, 0x74, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x53, 0x0a, 0x0d, 0x47,
	0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x79, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x6d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x08, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x69, 0x6e, 0x2e, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x08, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x22, 0x97, 0x01, 0x0a, 0x08, 0x47, 0x4d, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x65, 0x73, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x69, 0x6e, 0x2e, 0x47, 0x4d, 0x52, 0x65, 0x70,
	0x6c, 0x61, 0x79, 0x42, 0x79, 0x74, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a,
	0x09, 0x6a, 0x73, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6a, 0x73, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x22, 0x31, 0x0a, 0x0c, 0x47, 0x4d,
	0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x42, 0x79, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65,
	0x64, 0x69, 0x73, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x22, 0x45, 0x0a,
	0x08, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x22, 0x0a, 0x03, 0x61, 0x64, 0x64,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x69, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x61, 0x64, 0x64, 0x12, 0x15, 0x0a,
	0x06, 0x64, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x05, 0x64,
	0x65, 0x6c, 0x49, 0x64, 0x22, 0x6e, 0x0a, 0x0c, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x65, 0x6e, 0x64, 0x2a, 0x37, 0x0a, 0x02, 0x49, 0x44, 0x12, 0x17, 0x0a, 0x13, 0x47, 0x52,
	0x50, 0x43, 0x5f, 0x47, 0x4d, 0x5f, 0x43, 0x4d, 0x44, 0x5f, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c,
	0x54, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x47, 0x52, 0x50, 0x43, 0x5f, 0x47, 0x4d, 0x5f, 0x43,
	0x4d, 0x44, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x49, 0x54, 0x59, 0x10, 0x01, 0x32, 0x63, 0x0a,
	0x0a, 0x57, 0x65, 0x62, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x47,
	0x52, 0x50, 0x43, 0x54, 0x65, 0x73, 0x74, 0x12, 0x0f, 0x2e, 0x69, 0x6e, 0x2e, 0x54, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x69, 0x6e, 0x2e, 0x54, 0x65,
	0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x05, 0x47, 0x4d,
	0x43, 0x6d, 0x64, 0x12, 0x0d, 0x2e, 0x69, 0x6e, 0x2e, 0x47, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x69, 0x6e, 0x2e, 0x47, 0x4d, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79,
	0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x69, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_in_ssws_proto_rawDescOnce sync.Once
	file_common_in_ssws_proto_rawDescData = file_common_in_ssws_proto_rawDesc
)

func file_common_in_ssws_proto_rawDescGZIP() []byte {
	file_common_in_ssws_proto_rawDescOnce.Do(func() {
		file_common_in_ssws_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_in_ssws_proto_rawDescData)
	})
	return file_common_in_ssws_proto_rawDescData
}

var file_common_in_ssws_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_in_ssws_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_common_in_ssws_proto_goTypes = []interface{}{
	(ID)(0),               // 0: in.ID
	(*TestRequest)(nil),   // 1: in.TestRequest
	(*TestReplay)(nil),    // 2: in.TestReplay
	(*GMRequest)(nil),     // 3: in.GMRequest
	(*GMRequestByte)(nil), // 4: in.GMRequestByte
	(*GMReplay)(nil),      // 5: in.GMReplay
	(*GMReplayByte)(nil),  // 6: in.GMReplayByte
	(*Activity)(nil),      // 7: in.Activity
	(*ActivityInfo)(nil),  // 8: in.ActivityInfo
}
var file_common_in_ssws_proto_depIdxs = []int32{
	4, // 0: in.GMRequest.data:type_name -> in.GMRequestByte
	7, // 1: in.GMRequestByte.activity:type_name -> in.Activity
	6, // 2: in.GMReplay.data:type_name -> in.GMReplayByte
	8, // 3: in.Activity.add:type_name -> in.ActivityInfo
	1, // 4: in.WebService.GRPCTest:input_type -> in.TestRequest
	3, // 5: in.WebService.GMCmd:input_type -> in.GMRequest
	2, // 6: in.WebService.GRPCTest:output_type -> in.TestReplay
	5, // 7: in.WebService.GMCmd:output_type -> in.GMReplay
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_common_in_ssws_proto_init() }
func file_common_in_ssws_proto_init() {
	if File_common_in_ssws_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_in_ssws_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_in_ssws_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestReplay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_in_ssws_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GMRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_in_ssws_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GMRequestByte); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_in_ssws_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GMReplay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_in_ssws_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GMReplayByte); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_in_ssws_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Activity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_in_ssws_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_in_ssws_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_in_ssws_proto_goTypes,
		DependencyIndexes: file_common_in_ssws_proto_depIdxs,
		EnumInfos:         file_common_in_ssws_proto_enumTypes,
		MessageInfos:      file_common_in_ssws_proto_msgTypes,
	}.Build()
	File_common_in_ssws_proto = out.File
	file_common_in_ssws_proto_rawDesc = nil
	file_common_in_ssws_proto_goTypes = nil
	file_common_in_ssws_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WebServiceClient is the client API for WebService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WebServiceClient interface {
	GRPCTest(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestReplay, error)
	GMCmd(ctx context.Context, in *GMRequest, opts ...grpc.CallOption) (*GMReplay, error)
}

type webServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebServiceClient(cc grpc.ClientConnInterface) WebServiceClient {
	return &webServiceClient{cc}
}

func (c *webServiceClient) GRPCTest(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestReplay, error) {
	out := new(TestReplay)
	err := c.cc.Invoke(ctx, "/in.WebService/GRPCTest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webServiceClient) GMCmd(ctx context.Context, in *GMRequest, opts ...grpc.CallOption) (*GMReplay, error) {
	out := new(GMReplay)
	err := c.cc.Invoke(ctx, "/in.WebService/GMCmd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebServiceServer is the server API for WebService service.
type WebServiceServer interface {
	GRPCTest(context.Context, *TestRequest) (*TestReplay, error)
	GMCmd(context.Context, *GMRequest) (*GMReplay, error)
}

// UnimplementedWebServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWebServiceServer struct {
}

func (*UnimplementedWebServiceServer) GRPCTest(context.Context, *TestRequest) (*TestReplay, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GRPCTest not implemented")
}
func (*UnimplementedWebServiceServer) GMCmd(context.Context, *GMRequest) (*GMReplay, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GMCmd not implemented")
}

func RegisterWebServiceServer(s *grpc.Server, srv WebServiceServer) {
	s.RegisterService(&_WebService_serviceDesc, srv)
}

func _WebService_GRPCTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServiceServer).GRPCTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/in.WebService/GRPCTest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServiceServer).GRPCTest(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebService_GMCmd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServiceServer).GMCmd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/in.WebService/GMCmd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServiceServer).GMCmd(ctx, req.(*GMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WebService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "in.WebService",
	HandlerType: (*WebServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GRPCTest",
			Handler:    _WebService_GRPCTest_Handler,
		},
		{
			MethodName: "GMCmd",
			Handler:    _WebService_GMCmd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/in/ssws.proto",
}
